### ISSUE TITLE
Popover disappearing on page scroll even with auto_dismiss=False

### ISSUE THREAD

**Issue by jshaffstall** [anvilistas/anvil-extras#268] opened 2022-02-09 03:15 UTC
**Describe the bug**

A popover created with auto_dismiss=False disappears when the page scrolls.  This creates a problem when it's the popover itself that is extending beyond the bottom of the page and the user needs to scroll to read it all.

**To Reproduce**

Using this app: https://anvil.works/build#clone:YV6TXJX6VEUJGJD7=LE4R7H7QBXMYW7QHMAJPCZRU

1) Run the app and size the window so that vertical scrollbars are present
2) Click any button to show a popover
3) Scroll the window and the popover disappears

**Expected behavior**

With auto_dismiss=False, I'd expect the popover to remain showing and to scroll with the rest of the page, maintaining its relative position to the other components.  This would allow the user to scroll to read the popover content if needed.

**I am considering making a PR for this issue**

No.

**Comment by s-cork** [comment] 2022-02-09 05:43
Easy fix - change the placement to `"auto bottom"` instead of just `"bottom"`
_TODO document this_

`auto_dismiss` is just about whether the popovers should be dismissed on outside click or not.

I've spent a little time thinking about this.
I have a solution but I don't know if I have a working API in the general case.

The problem is in the HTML of the page.

Currently we attach popovers to the body of the page:
- benefit - always visible - some components have overflow issues
- BUT - the body is not what is being scrolled - so the decision was taken to just hide popovers on scroll since popovers stayed fixed on the page rather than scrolling with their popper element.

In material design the `.content` element is fixed and its children scroll.
So in material design we'd want to create a child element of `.content` to be the container for the popovers (instead of `body`).

If I create this element and remove the code that hides things on scroll then it's 😍.
But that's not a working API!

Possible solution:
If you really know what you're doing

```python
# global function overrides all
def dismiss_on_scroll(dismiss=True):
     ...


def popover(..., dismiss_on_scroll=True, container="body"):
    ...
```

Thoughts...
Here's your clone with the API: https://anvil.works/build#clone:MYWXZC4622BTW6RK=QDCF33O74M4W5ONFDKUDXMWI

**Comment by jshaffstall** [comment] 2022-02-09 21:41
Adding `auto` to placement defers the issue, but if they scroll the popover will still go away.  I'm using popovers for an in-app tutorial, and it's important the popovers not go away until they're supposed to (e.g. the user clicks a button on the popover itself, or does whatever the tutorial step is telling them to do).

The dismiss_on_scroll API does exactly what I'm looking for.

**Comment by s-cork** [comment] 2022-02-09 23:07
Great. It would be an advanced feature since you'd also have to change the container property to make it work. 

I could make this global too like
`set_default_container`
In the same way we have a default width. 

And maybe have a helper for material design. Or maybe just document how to do it in material design.

**Closed** 2022-02-10 08:59 UTC
Labels: possible bug
